# Generated by Django 3.2.13 on 2022-06-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('LANDLORD_OR_ESTATEAGENT', 'Landlord or Estate Agent'), ('TENANT', 'Tenant')], default='Tenant', max_length=30),
        ),
    ]
