# Generated by Django 3.2.13 on 2022-06-20 14:51

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('address_street', models.CharField(blank=True, max_length=100, null=True)),
                ('address_street2', models.CharField(blank=True, max_length=100, null=True)),
                ('address_town', models.CharField(blank=True, max_length=50, null=True)),
                ('address_county', models.CharField(blank=True, max_length=50, null=True, verbose_name='County/Province/State')),
                ('address_postcode', models.CharField(max_length=35, verbose_name='Postal Code/Zip Code')),
                ('address_country', models.CharField(blank=True, max_length=75, null=True)),
                ('num_of_bedrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('num_of_bathrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('type_of_property', models.CharField(choices=[('1', 'Flat'), ('2', 'Terrace house'), ('3', 'Semi-detached house'), ('4', 'Detached house'), ('5', 'Bungalow'), ('6', 'House share')], default=1, max_length=30)),
                ('for_rent', models.BooleanField(default=False)),
                ('images', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('ll_or_ea', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Landlord/Estate Agent')),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_on', 'title'],
            },
        ),
    ]
