# Generated by Django 3.2.13 on 2022-06-17 12:11

import address.models
import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('num_of_bedrooms', models.PositiveIntegerField()),
                ('num_of_bathrooms', models.PositiveIntegerField()),
                ('type_of_property', models.CharField(choices=[('1', 'Condition of property'), ('2', 'Quality of landlord'), ('3', 'Rate the neighbourhood'), ('4', 'Standard of amenities nearby'), ('5', 'Value for money')], default=1, max_length=30)),
                ('for_rent', models.BooleanField(default=False)),
                ('images', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('address', address.models.AddressField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address', unique=True)),
                ('ll_or_ea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Landlord/Estate Agent')),
            ],
            options={
                'ordering': ['-created_on', 'title'],
            },
        ),
    ]
