# Generated by Django 3.2.13 on 2022-06-20 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='address_street',
            new_name='street_address',
        ),
    ]
