# Generated by Django 3.2.13 on 2022-06-28 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='type_of_property',
            field=models.CharField(choices=[('Flat', 'Flat'), ('Terrace house', 'Terrace house'), ('Semi-detached house', 'Semi-detached house'), ('Detached house', 'Detached house'), ('Bungalow', 'Bungalow'), ('House share', 'House share')], default=0, max_length=30),
        ),
    ]
