# Generated by Django 3.2.13 on 2022-07-23 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0002_alter_property_type_of_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='ll_or_ea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Landlord/Estate Agent'),
        ),
    ]
