# Generated by Django 3.2.13 on 2022-06-20 16:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_auto_20220620_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='images',
            field=cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, null=True, verbose_name='image'),
        ),
    ]
