# Generated by Django 3.2.13 on 2022-06-20 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_property_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('0', 'Draft'), ('1', 'Published')], default=0, max_length=30),
        ),
    ]
