# Generated by Django 3.2.13 on 2022-06-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_auto_20220618_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='num_of_bathrooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='num_of_bedrooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
