# Generated by Django 3.2.13 on 2022-06-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_property_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('0', 'Draft'), ('1', 'Published')], default=1, max_length=30),
        ),
        migrations.AlterField(
            model_name='property',
            name='type_of_property',
            field=models.CharField(choices=[('1', 'Flat'), ('2', 'Terrace house'), ('3', 'Semi-detached house'), ('4', 'Detached house'), ('5', 'Bungalow'), ('6', 'House share')], default=0, max_length=30),
        ),
    ]
