# Generated by Django 3.2.13 on 2022-06-19 16:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0006_auto_20220619_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('date_rented_from', models.DateField(blank=True, null=True)),
                ('date_rented_to', models.DateField(blank=True, null=True)),
                ('content', models.TextField(blank=True, max_length=500, null=True)),
                ('condition_of_property', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('quality_of_landlord', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('rate_the_neighbourhood', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('value_for_money', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('standard_of_amenities_nearby', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('date_reviewed', models.DateTimeField(auto_now_add=True)),
                ('likes', models.ManyToManyField(blank=True, null=True, related_name='review_likes', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
