# Generated by Django 3.2.13 on 2022-06-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='overall_rating',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
