# Generated by Django 3.2.13 on 2022-06-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_overall_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='overall_rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
