# Generated by Django 3.2.13 on 2022-06-20 19:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_overall_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='images',
            field=cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, null=True, verbose_name='image'),
        ),
    ]
